# CMake generated Testfile for 
# Source directory: E:/DATA/vscode/ARIS/FLUXMEMO
# Build directory: E:/DATA/vscode/ARIS/FLUXMEMO/build_dll
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_crc32c "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/Debug/test_crc32c.exe")
  set_tests_properties(test_crc32c PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;75;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_crc32c "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/Release/test_crc32c.exe")
  set_tests_properties(test_crc32c PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;75;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_crc32c "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/MinSizeRel/test_crc32c.exe")
  set_tests_properties(test_crc32c PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;75;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_crc32c "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/RelWithDebInfo/test_crc32c.exe")
  set_tests_properties(test_crc32c PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;75;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
else()
  add_test(test_crc32c NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_record_codec "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/Debug/test_record_codec.exe")
  set_tests_properties(test_record_codec PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;76;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_record_codec "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/Release/test_record_codec.exe")
  set_tests_properties(test_record_codec PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;76;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_record_codec "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/MinSizeRel/test_record_codec.exe")
  set_tests_properties(test_record_codec PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;76;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_record_codec "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/RelWithDebInfo/test_record_codec.exe")
  set_tests_properties(test_record_codec PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;76;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
else()
  add_test(test_record_codec NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_store_mvcc "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/Debug/test_store_mvcc.exe")
  set_tests_properties(test_store_mvcc PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;77;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_store_mvcc "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/Release/test_store_mvcc.exe")
  set_tests_properties(test_store_mvcc PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;77;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_store_mvcc "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/MinSizeRel/test_store_mvcc.exe")
  set_tests_properties(test_store_mvcc PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;77;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_store_mvcc "E:/DATA/vscode/ARIS/FLUXMEMO/build_dll/bin/RelWithDebInfo/test_store_mvcc.exe")
  set_tests_properties(test_store_mvcc PROPERTIES  _BACKTRACE_TRIPLES "E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;72;add_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;77;flux_test;E:/DATA/vscode/ARIS/FLUXMEMO/CMakeLists.txt;0;")
else()
  add_test(test_store_mvcc NOT_AVAILABLE)
endif()
